<?php
define("SYSTEMDK_GUESTBOOK_METAKEYWORDS","Гостевая книга, гостевая, отзывы, SystemDK, отзывы SystemDK, Guestbook, SystemDK comments");
define("SYSTEMDK_GUESTBOOK_METADESCRIPTION","Гостевая книга Guestbook");
define("SYSTEMDK_GUESTBOOK_STORYNUM",10);
define("SYSTEMDK_GUESTBOOK_ANTISPAM_IPADDR","yes");
define("SYSTEMDK_GUESTBOOK_ANTISPAM_NUM",10);
define("SYSTEMDK_GUESTBOOK_CONFIRM_NEED","yes");
define("SYSTEMDK_GUESTBOOK_SORTORDER","DESC");
?>
